# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting_window(object):
    def setupUi(self, Setting_window):
        Setting_window.setObjectName("Setting_window")
        Setting_window.resize(206, 110)
        Setting_window.setMinimumSize(QtCore.QSize(206, 110))
        Setting_window.setMaximumSize(QtCore.QSize(206, 110))
        self.centralwidget = QtWidgets.QWidget(Setting_window)
        self.centralwidget.setObjectName("centralwidget")
        self.COM = QtWidgets.QComboBox(self.centralwidget)
        self.COM.setGeometry(QtCore.QRect(60, 10, 141, 22))
        self.COM.setObjectName("COM")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(114, 40, 81, 23))
        self.pushButton.setObjectName("pushButton")
        Setting_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Setting_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 206, 21))
        self.menubar.setObjectName("menubar")
        Setting_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Setting_window)
        self.statusbar.setObjectName("statusbar")
        Setting_window.setStatusBar(self.statusbar)

        self.retranslateUi(Setting_window)
        QtCore.QMetaObject.connectSlotsByName(Setting_window)

    def retranslateUi(self, Setting_window):
        _translate = QtCore.QCoreApplication.translate
        Setting_window.setWindowTitle(_translate("Setting_window", "Setting"))
        self.label.setText(_translate("Setting_window", "COM"))
        self.pushButton.setText(_translate("Setting_window", "Enter"))
